class PagesController < ApplicationController
  def layout
    @cards = [
      {title: "Lobbying for policy change", action: "Advocating"},
      {title: "Influencing government and business priorities", action: "Advocating"},
      {title: "Influencing public opinion", action: "Advocating"},
      {title: "Promoting specific organizations and interventions", action: "Advocating"},
      {title: "Providing direct support to local government", action: "Building Community Capacity"},
      {title: "Growing local entrepreneurs and businesses", action: "Building Community Capacity"},
      {title: "Promoting nonprofit organizational effectiveness", action: "Building Community Capacity"},
      {title: "Developing the skills of local residents", action: "Building Community Capacity"},
      {title: "Empowering resident decision-making", action: "Engaging The Community"},
      {title: "Mobilizing residents around issues", action: "Engaging The Community"},
      {title: "Providing avenues for community input, ideas and connection", action: "Engaging The Community"},
      {title: "Facilitating civic participation and volunteerism", action: "Engaging The Community"},
      {title: "Facilitating community dialogue", action: "Engaging The Community"},
      {title: "Strengthening social connections among residents", action: "Engaging The Community"},
      {title: "Proactively planning for the long term", action: "Community Planning"},
      {title: "Facilitating urban/ rural planning processes", action: "Community Planning"},
      {title: "Promoting economic development planning", action: "Community Planning"},
      {title: "Planning for disaster response and prevention", action: "Community Planning"},
      {title: "Soliciting giving from local donors (individual or institutional)", action: "Expanding Financial Capital"},
      {title: "Soliciting capital from outside the community", action: "Expanding Financial Capital"},
      {title: "Deliberately attracting diverse donors", action: "Expanding Financial Capital"},
      {title: "Educating the public about philanthropy", action: "Expanding Financial Capital"},
      {title: "Developing earned income to support social-purpose activities", action: "Expanding Financial Capital"},
      {title: "Facilitating learning networks", action: "Aligning Action"},
      {title: "Managing formal collaborations", action: "Aligning Action"},
      {title: "Coordinating funding and activities", action: "Aligning Action"},
      {title: "Building collaboratives", action: "Aligning Action"},
      {title: "Incubating social enterprises or businesses", action: "Direct Service & Programming"},
      {title: "Starting new nonprofit programs", action: "Direct Service & Programming"},
      {title: "Managing direct service programs", action: "Direct Service & Programming"},
      {title: "Designing government interventions", action: "Direct Service & Programming"},
      {title: "Managing government programs", action: "Direct Service & Programming"},
      {title: "Impact investing", action: "Deploying Financial Capital"},
      {title: "Supporting individuals (scholarships, fellowships, etc.)", action: "Deploying Financial Capital"},
      {title: "Grantmaking to nonprofits", action: "Deploying Financial Capital"},
      {title: "Directly connecting givers and recipients", action: "Deploying Financial Capital"},
      {title: "Managing transactions for donors", action: "Financial & Donor Services"},
      {title: "Educating donors about community issues", action: "Financial & Donor Services"},
      {title: "Managing investments/ endowment funds", action: "Financial & Donor Services"},
      {title: "Providing philanthropic advisory services", action: "Financial & Donor Services"},
      {title: "Connecting local philanthropists with each other", action: "Financial & Donor Services"},
      {title: "Co-creating initiatives with donors", action: "Financial & Donor Services"},
      {title: "Tracking data about community well-being", action: "Sharing Community Information"},
      {title: "Compiling information about local organizations and available resources", action: "Sharing Community Information"},
      {title: "Researching community issues and public policy", action: "Sharing Community Information"},
      {title: "Measuring the outcomes and impacts of programs", action: "Sharing Community Information"},
      {title: "Spreading local news", action: "Sharing Community Information"}
    ]
  end
end
